CREATE TABLE `p_code_gen_records` (
                                      `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '序号',
                                      `inserttime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
                                      `updatetime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                      `isactive` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否逻辑删除',
                                      `delete_token` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NA' COMMENT '逻辑删除标记',
                                      `generate_uuid` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '生成代码的uuid',
                                      `generate_type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '生成代码类型',
                                      `is_single_line` tinyint(1) NOT NULL COMMENT '是否单行生成',
                                      `git_repo` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'git 仓库地址',
                                      `git_branch` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'git 分支',
                                      `code_path` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码路径',
                                      `code_language` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码语言',
                                      `ide_info` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ide 信息',
                                      `start_cursor_idx` int unsigned NOT NULL COMMENT '代码生成时光标开始位置',
                                      `prefix_code_tokens` int unsigned NOT NULL COMMENT '光标前的代码 token',
                                      `suffix_code_tokens` int unsigned NOT NULL COMMENT '光标后的代码 token',
                                      `model_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模型名称',
                                      `model_version` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模型版本',
                                      `code_total_lines` int NOT NULL COMMENT '代码总行数',
                                      `crossfile_ctx_nums` int NOT NULL COMMENT '跨文件片段总数',
                                      `prompt_tokens` int unsigned DEFAULT NULL COMMENT 'prompt token',
                                      `completion_code` text COLLATE utf8mb4_unicode_ci COMMENT '生成代码',
                                      `completion_duration` int unsigned DEFAULT NULL COMMENT '生成代码耗时',
                                      `completion_code_tokens` int unsigned DEFAULT NULL COMMENT '生成代码 token',
                                      `completion_code_lines` int unsigned DEFAULT NULL COMMENT '生成代码行数',
                                      `finish_reason` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '完成原因',
                                      `failure_reason` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '失败原因',
                                      `accept_status` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户接受生成代码状态',
                                      `create_user` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '创建人',
                                      PRIMARY KEY (`id`),
                                      UNIQUE KEY `uniq_code_gen_records` (`generate_uuid`,`delete_token`),
                                      KEY `idx_updatetime` (`updatetime`),
                                      KEY `idx_inserttime` (`inserttime`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='代码生成记录表';

CREATE TABLE `p_code_gen_retrieval_snippet_map` (
                                                    `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '序号',
                                                    `inserttime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
                                                    `updatetime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                    `isactive` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否逻辑删除',
                                                    `delete_token` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NA' COMMENT '逻辑删除标记',
                                                    `generate_uuid` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '生成代码 uuid',
                                                    `git_repo` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'git 仓库地址',
                                                    `git_branch` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'git 分支',
                                                    `snippet_uuid` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '检索代码片段 uuid',
                                                    `snippet_score` decimal(5,2) NOT NULL COMMENT '检索代码片段得分',
                                                    `snippet_repo` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '检索代码片段 git 仓库',
                                                    `snippet_path` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '检索代码片段路径',
                                                    `snippet_content` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '检索代码片段内容',
                                                    `project_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '插件名称',
                                                    `project_version` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '插件版本',
                                                    `create_user` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '创建人',
                                                    PRIMARY KEY (`id`),
                                                    UNIQUE KEY `uniq_code_gen_retrieval_snippet_map` (`generate_uuid`,`snippet_uuid`,`delete_token`),
                                                    KEY `idx_updatetime` (`updatetime`),
                                                    KEY `idx_inserttime` (`inserttime`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='代码生成与检索片段关联表';

CREATE TABLE `p_chat_records` (
                                  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '序号',
                                  `inserttime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
                                  `updatetime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                  `isactive` tinyint(1) NOT NULL DEFAULT '1' COMMENT '逻辑删除',
                                  `delete_token` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NA' COMMENT '逻辑删除标志',
                                  `conversation_uuid` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '会话 uuid',
                                  `git_repo` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'git 仓库',
                                  `git_branch` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'git 分支',
                                  `code_path` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码路径',
                                  `code_language` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码语言',
                                  `ide_info` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ide 版本信息',
                                  `project_name` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '插件名称',
                                  `project_version` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '插件版本',
                                  `engine_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模型名称',
                                  `model_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模型名称',
                                  `model_version` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模型版本',
                                  `prompt_tokens` int unsigned DEFAULT NULL COMMENT 'prompt tokens',
                                  `completion_tokens` int unsigned DEFAULT NULL COMMENT '生成代码 tokens',
                                  `total_tokens` int unsigned DEFAULT NULL COMMENT 'total tokens',
                                  `completion_code_lines` int unsigned DEFAULT NULL COMMENT '生成代码行数',
                                  `completion_duration` int unsigned DEFAULT NULL COMMENT '生成代码耗时',
                                  `failure_reason` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会话失败原因',
                                  `accept_status` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会话是否被采纳',
                                  `conversation_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '会话类型',
                                  `prompt_tmpl_version` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'prompt 版本',
                                  `prompt_tmpl_content` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'prompt 内容',
                                  `create_user` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '创建人',
                                  PRIMARY KEY (`id`),
                                  UNIQUE KEY `uniq_chat_records` (`conversation_uuid`,`delete_token`),
                                  KEY `idx_updatetime` (`updatetime`),
                                  KEY `idx_inserttime` (`inserttime`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='聊天会话记录表';
